---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Hello_Flagger
  labels:
    app: Hello_Flagger
spec:
  selector:
    matchLabels:
      app: Hello_Flagger
  template:
    metadata:
      labels:
        app: Hello_Flagger
    spec:
      containers:
      - name: Hello_Flagger
        image: siteshm/hello:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health-check
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health-check
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
