---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v1
  labels:
    app: helloworld
    version: v1
spec:
  replicas: CANARY_REPLICAS
  selector:
    matchLabels:
      app: helloworld
      version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: MaxSurge
      maxUnavailable: MaxUnavailable
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
      - name: helloworld
        image: siteshm/helloworld:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health-check
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health-check
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
