---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flagger
  labels:
    app: hello-flagger
spec:
  selector:
    matchLabels:
      app: hello-flagger
  template:
    metadata:
      labels:
        app: hello-flagger
    spec:
      containers:
      - name: hello-flagger
        image: siteshm/helloworldeks:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health-check
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health-check
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
