---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: hello-flagger
spec:
  provider: istio
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-flagger
  progressDeadlineSeconds: 60
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: hello-flagger
  service:
    port: 5000
    targetPort: 5000
    name: hello-flagger
    gateways:
    - hello-gateway
    hosts:
    - "*"
  analysis:
    interval: 1m
    threshold: 3
    maxWeight: 60
    stepWeight: 20
    metrics:
    - name: request-success-rate
      threshold: 99
      interval: 1m
    - name: latency
      templateRef:
        name: latency
      thresholdRange:
        max: 1000
      interval: 1m

---

apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: latency
spec:
  provider:
    type: prometheus
    address: http://prometheus.istio-system:9090
  query: |
    histogram_quantile(
        0.99,
        sum(
            rate(
                istio_request_duration_milliseconds_bucket{
                    reporter="destination",
                    destination_workload_namespace="{{ namespace }}",
                    destination_workload=~"{{ target }}"
                }[{{ interval }}]
            )
        ) by (le)
    )
