---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: Hello_Flagger
spec:
  provider: istio
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: Hello_Flagger
  progressDeadlineSeconds: 60
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: Hello_Flagger
  service:
    port: 80
    targetPort: 5000
    gateways:
    - hello-gateway
    hosts:
    - "*"
  analysis:
    interval: 1m
    threshold: 3
    maxWeight: 60
    stepWeight: 20
