---
apiVersion: v1
kind: Service
metadata:
  name: hello-flagger
  labels:
    app: hello-flagger
    service: hello-flagger
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: hello-flagger
  type: LoadBalancer
